CREATE TABLE AuditLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    AccountID NUMBER,
    TransactionDate DATE,
    Amount NUMBER,
    TransactionType VARCHAR2(10),
    LogDate DATE
);


CREATE OR REPLACE TRIGGER LogTransaction
AFTER 
INSERT 
ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (TransactionID, AccountID, TransactionDate, Amount, TransactionType, LogDate)
    VALUES (:NEW.TransactionID, :NEW.AccountID, :NEW.TransactionDate, :NEW.Amount, :NEW.TransactionType, SYSDATE);
END;
/

INSERT INTO Transactions (TransactionID, AccountID, TransactionDate, Amount, TransactionType) 
VALUES (1, 1, SYSDATE, 100, 'Deposit');

SELECT * FROM AuditLog;


/*
OUTPUT 


LogID  TransactionID  AccountID  TransactionDate  Amount  TransactionType    LogDate
---------------------------------------------------------------------------------------------
1      1              1          2024-08-06        100     Deposit           2024-08-06
*/